{ Formatters vs Foundation's ByteCountFormatter (Formatters.swift).

  tests/data/bytecount_<locale>.tsv hold byte count, formatFileSize and the
  raw decimal GB/TB string from the real formatter, generated by
  tests/data/bytecount_truth.swift (run with -AppleLocale en_US, and in an
  en_PL locale). Each table is checked with that locale's separators. }

program test_formatters;

{$mode objfpc}{$H+}

uses
  SysUtils, Classes, Formatters;

var
  Fail: Boolean;

{ Swift's formatDecimalNoFraction: drop the first '.' or ',' run of digits. }
function SwiftNoFraction(const S: string): string;
var
  I, J: Integer;
begin
  Result := S;
  for I := 1 to Length(Result) - 1 do
    if (Result[I] in ['.', ',']) and (Result[I + 1] in ['0'..'9']) then
    begin
      J := I + 1;
      while (J <= Length(Result)) and (Result[J] in ['0'..'9']) do
        Inc(J);
      Delete(Result, I, J - I);
      Exit;
    end;
end;

procedure CheckTable(const FileName, DecimalSep, GroupSep: string);
var
  Lines, Cols: TStringList;
  I, Checked, Bad: Integer;
  Bytes: Int64;
  Got: string;
begin
  Lines := TStringList.Create;
  Cols := TStringList.Create;
  try
    Lines.LoadFromFile(FileName);
    Cols.Delimiter := #9;
    Cols.StrictDelimiter := True;
    Checked := 0;
    Bad := 0;
    for I := 0 to Lines.Count - 1 do
    begin
      if Lines[I] = '' then
        Continue;
      Cols.DelimitedText := Lines[I];
      Bytes := StrToInt64(Cols[0]);
      Got := FormatFileSizeWith(Bytes, DecimalSep, GroupSep);
      if Got <> Cols[1] then
      begin
        WriteLn('  ', Bytes, ': file got "', Got, '" want "', Cols[1], '"');
        Inc(Bad);
      end;
      Got := FormatDecimalNoFractionWith(Bytes, DecimalSep, GroupSep);
      if Got <> SwiftNoFraction(Cols[2]) then
      begin
        WriteLn('  ', Bytes, ': no-fraction got "', Got, '" want "',
          SwiftNoFraction(Cols[2]), '"');
        Inc(Bad);
      end;
      Inc(Checked);
    end;
    if Bad > 0 then
    begin
      WriteLn('FAIL: ', ExtractFileName(FileName), ': ', Bad, ' mismatches');
      Fail := True;
    end
    else
      WriteLn('ok: ', ExtractFileName(FileName), ': ', Checked,
        ' values match ByteCountFormatter');
  finally
    Cols.Free;
    Lines.Free;
  end;
end;

var
  Dir: string;
begin
  Fail := False;
  Dir := ExtractFilePath(ParamStr(0)) + 'data' + PathDelim;
  CheckTable(Dir + 'bytecount_en_US.tsv', '.', ',');
  CheckTable(Dir + 'bytecount_en_PL.tsv', ',', '.');
  if Fail then
    Halt(1);
  WriteLn('test_formatters: all passed');
end.
